spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

mail:
  info:
    receiver: ${RECEIVER_MAIL}
    subject: "Pillolina Time"
    message: |
      <html>
        <body>
          <p>Ciao Amore mio,</p>
          <p>E' ora di prendere la pillolina</p>
          <a href="https://dreadful-jandy-fttroy-350ad142.koyeb.app/" style="
              background-color: #FFC0CB;
              color: white;
              padding: 10px 20px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
              border-radius: 5px;">
            Clicca per confermare di averla presa!
          </a>
        </body>
      </html>

scheduled:
  cron: ${SEND_TIME}

